"use client";

import { Suspense, useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import Link from "next/link";

function ResetForm() {
  const params = useSearchParams(); const router = useRouter();
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setMessage(""); if (password !== confirm) { setMessage("Las contraseñas no coinciden."); return; } setBusy(true); try { const apiUrl = process.env.NEXT_PUBLIC_API_URL || "https://pikagamesapiweb.vercel.app/api"; const response = await fetch(`${apiUrl}/auth/reset-password`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: params.get("token"), newPassword: password }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "El enlace no es válido o ya expiró."); setMessage(data.message); setTimeout(() => router.push("/"), 1200); } catch (error) { setMessage(error instanceof Error ? error.message : "No se pudo restablecer la contraseña."); } finally { setBusy(false); } };
  return <main className="flex min-h-screen items-center justify-center bg-[#111311] px-4 text-zinc-200"><section className="w-full max-w-md rounded-3xl border border-zinc-800 bg-zinc-900 p-6 shadow-2xl sm:p-8"><p className="mb-2 text-sm font-bold uppercase tracking-widest text-[#ffd90f]">PikaGames</p><h1 className="text-2xl font-black text-white">Crea una nueva contraseña</h1><p className="mt-2 text-sm text-zinc-400">Elige una contraseña segura para volver a entrar a tu cuenta.</p><form onSubmit={submit} className="mt-6 space-y-5"><div><label htmlFor="reset-password" className="mb-2 block text-sm font-medium text-zinc-300">Nueva contraseña</label><input id="reset-password" type="password" minLength={8} required autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} className="min-h-12 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 text-white focus-visible:border-[#ffd90f] focus-visible:outline-none" /></div><div><label htmlFor="reset-confirm" className="mb-2 block text-sm font-medium text-zinc-300">Confirmar contraseña</label><input id="reset-confirm" type="password" minLength={8} required autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="min-h-12 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-4 text-white focus-visible:border-[#ffd90f] focus-visible:outline-none" /></div>{message && <p role="status" className="text-sm text-zinc-300">{message}</p>}<button type="submit" disabled={busy} className="w-full rounded-xl bg-[#ffd90f] px-4 py-3 font-bold text-zinc-900 disabled:opacity-60">{busy ? "Guardando…" : "Guardar nueva contraseña"}</button></form><Link href="/" className="mt-5 block text-center text-sm font-bold text-[#ffd90f]">Volver a PikaGames</Link></section></main>;
}

export default function ResetPasswordPage() { return <Suspense fallback={<main className="min-h-screen bg-[#111311]" />}><ResetForm /></Suspense>; }
